---
#Installs All Packages
- name: Install Packages from APT
  apt:
    name: "{{ packages }}"
    state: build-dep
  vars:
    packages:
     - apt-transport-https
     - gnupg
     - gnupg-agent 
     - htop
     - hollywood
     - cmatrix
     - ranger
     - neofetch
     - unzip
     - meld
     - python3
     - python3-pip
     - nodejs
     - npm
     - binutils
     - curl
     - ghex
     - openssl
     - vim
     - jq
     - ca-certificates
     - apt-transport-https 
     - lsb-release 
     - dkms
     - python3-requests
     - snapd
     - virtualbox
     - xclip
     - nano
     - ncdu
     - zsh


- name: Remove Packages with APT (test)
  apt:
    name: "{{ packages }}"
    state: absent
  vars:
    packages:
    - gimp
