- name: Create .ssh Folder
  file: 
    path: /home/ansible/.ssh
    owner: ansible 
    group: ansible 
    mode: 0755 
    state: directory

- name: Generate deploy key
  openssh_keypair:
    path: /home/ansible/.ssh/github_deploykey
    #owner: ansible

