---
- name: Install Goolge Chrome
  apt: 
    deb: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb     

- name: Install Microsoft Teams Insider
  apt:
    deb: https://packages.microsoft.com/repos/ms-teams/pool/main/t/teams-insiders/teams-insiders_1.4.00.4855_amd64.deb

- name: Install Powershell 7.1.2
  apt:
    deb: https://github.com/PowerShell/PowerShell/releases/download/v7.1.2/powershell_7.1.2-1.ubuntu.20.04_amd64.deb
