- name: Download  Micirsoft's GPG Key
  shell: curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
  args:
    executable: /bin/bash
    warn: false

- name: Install Micirsoft's GPG Key
  shell: install -o root -g root -m 644 packages.microsoft.gpg /usr/share/keyrings/
  become: yes
  args:
    executable: /bin/bash
    
- name: Add the VS Code repository
  apt_repository:
    repo: 'deb [arch=amd64]  https://packages.microsoft.com/repos/vscode stable main'
    state: present

- name: Update APT Sources
  apt:
    update_cache: yes

- name: Install VSCode
  apt: 
   pkg:
    code
