- name: Download and Install the Microsoft GPG Keys
  shell: wget -q https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb && sudo dpkg -i packages-microsoft-prod.deb
  become: yes
  args:
    executable: /bin/bash
    warn: false

- name: Update APT Sources
  apt:
    update_cache: yes

- name: Install Powershell
  apt:
    name: powershell
