- name: Download  Micirsoft's GPG Key
  shell: curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
  args:
    executable: /bin/bash
    warn: false

- name: Install Micirsoft's GPG Key
  shell: sudo install -o root -g root -m 644 packages.microsoft.gpg /usr/share/keyrings/
  become: yes
  args:
    executable: /bin/bash
    

- name: Add the VS Code repository
  shell: sudo sh -c 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
  become: yes
  args:
     executable: /bin/bash

- name: Update APT Sources
  apt:
    update_cache: yes

- name: Install VSCode
  apt: 
   pkg:
    code