- name: Download and Install the Microsoft GPG Keys
  shell: wget -q https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb && sudo dpkg -i packages-microsoft-prod.deb
  become: yes
  args:
    executable: /bin/bash
    warn: false

- name: Enable Universe Repositories
  apt_repository:
    become: yes
    repo: deb http://us.archive.ubuntu.com/ubuntu/ focal universe
    state: present

- name: Update APT Sources
  apt:
    become: yes
    update_cache: yes

- name: Install Powershell
  apt:
    become: yes
    name: powershell
